theme = "beautifulhugo"
baseURL = "https://rmhogervorst.nl/cleancode/"
languageCode = "en-us"
title = "Clean Code (and R-fun)"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"
    
[Params]
  subtitle = "Tips about clean R-code and reproducible work, but also fun!"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
  readingTime = true
  modifyLink = true


[Author]
  name = "Roel M. Hogervorst"
  website = "rmhogervorst.nl"
  email = "hogervorst.rm@gmail.com"
  keybase = "rmhogervorst"
  github = "RMHogervorst"
  gitlab = "rmhogervorst"
  bitbucket = "RMHogervorst"
  twitter = "RMHoge"
  linkedin = "rmhogervorst"
  stackoverflow = "users/5573955/roel-hogervorst"
 